baseURL = "http://cogumm.net/"
languageCode = "pt-BR"
googleAnalytics = ""
title = "CoGUMm.net"
theme = "github-style"
paginate = 5

[params]
  author = "Gabriel F. Vilar"
  description = "Apaixonado por Software Livre, Músicas, Jogos e uma boa mesa de RPG!"
  github = "cogumm"
  twitter = "cogumm"
  linkedin = "cogumm"
  telegram = "cogumm"
  email = "gabriel@cogumm.net"
  utterances = "cogumm/cogumm.github.io"
  avatar = "https://avatars3.githubusercontent.com/u/113603?s=460&v=4"
  url = "http://cogumm.net/"

[permalinks]
  posts = "/:year/:month/:title/"