---
- :desc: ""
  :when_not_human: "2011-06-02"
  :event_title: ZouGames
  :who: ZouGames
  :event_site: #
  :event_site_title: Agenda do evento
  :title: Encontro do grupo de programadores do ZouGames
  :title_link: #
  :where: "Natal, RN"
  :when: 02/06
